const DEFAULT_ERROR_CODE = 500;
const NOT_FOUND_ERROR_CODE = 404;
const INCORRECT_DATA_ERROR_CODE = 400;

module.exports = {
  DEFAULT_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INCORRECT_DATA_ERROR_CODE
};